-- animalface 튜닝 결과를 팬트랙 인물 DB에 반영
-- 동물상은 미디어 언급 기반 라벨, 성별은 동물상 정의가 성별마다 달라서 함께 저장한다
ALTER TABLE celebrities ADD COLUMN gender TEXT;        -- f|m
ALTER TABLE celebrities ADD COLUMN animal_face TEXT;   -- dog|cat|rabbit|...

INSERT INTO celebrities (id,name_ko,group_name,gender,animal_face,created_at,updated_at) VALUES ('icharlin_juni','주니','아이칠린','f','bear',strftime('%s','now'),strftime('%s','now')) ON CONFLICT(id) DO UPDATE SET gender=excluded.gender, animal_face=excluded.animal_face, updated_at=strftime('%s','now');
INSERT INTO celebrities (id,name_ko,group_name,gender,animal_face,created_at,updated_at) VALUES ('newjeans_haerin','해린','뉴진스','f','cat',strftime('%s','now'),strftime('%s','now')) ON CONFLICT(id) DO UPDATE SET gender=excluded.gender, animal_face=excluded.animal_face, updated_at=strftime('%s','now');
INSERT INTO celebrities (id,name_ko,group_name,gender,animal_face,created_at,updated_at) VALUES ('ive_liz','리즈','아이브','f','cat',strftime('%s','now'),strftime('%s','now')) ON CONFLICT(id) DO UPDATE SET gender=excluded.gender, animal_face=excluded.animal_face, updated_at=strftime('%s','now');
INSERT INTO celebrities (id,name_ko,group_name,gender,animal_face,created_at,updated_at) VALUES ('kissoflife_julie','쥴리','키스오브라이프','f','cat',strftime('%s','now'),strftime('%s','now')) ON CONFLICT(id) DO UPDATE SET gender=excluded.gender, animal_face=excluded.animal_face, updated_at=strftime('%s','now');
INSERT INTO celebrities (id,name_ko,group_name,gender,animal_face,created_at,updated_at) VALUES ('tripleS_jiwoo','이지우','트리플에스','f','chick',strftime('%s','now'),strftime('%s','now')) ON CONFLICT(id) DO UPDATE SET gender=excluded.gender, animal_face=excluded.animal_face, updated_at=strftime('%s','now');
INSERT INTO celebrities (id,name_ko,group_name,gender,animal_face,created_at,updated_at) VALUES ('newjeans_danielle','다니엘','뉴진스','f','deer',strftime('%s','now'),strftime('%s','now')) ON CONFLICT(id) DO UPDATE SET gender=excluded.gender, animal_face=excluded.animal_face, updated_at=strftime('%s','now');
INSERT INTO celebrities (id,name_ko,group_name,gender,animal_face,created_at,updated_at) VALUES ('lesserafim_chaewon','김채원','르세라핌','f','deer',strftime('%s','now'),strftime('%s','now')) ON CONFLICT(id) DO UPDATE SET gender=excluded.gender, animal_face=excluded.animal_face, updated_at=strftime('%s','now');
INSERT INTO celebrities (id,name_ko,group_name,gender,animal_face,created_at,updated_at) VALUES ('gong_yoo','공유',NULL,'m','dino',strftime('%s','now'),strftime('%s','now')) ON CONFLICT(id) DO UPDATE SET gender=excluded.gender, animal_face=excluded.animal_face, updated_at=strftime('%s','now');
INSERT INTO celebrities (id,name_ko,group_name,gender,animal_face,created_at,updated_at) VALUES ('kim_woobin','김우빈',NULL,'m','dino',strftime('%s','now'),strftime('%s','now')) ON CONFLICT(id) DO UPDATE SET gender=excluded.gender, animal_face=excluded.animal_face, updated_at=strftime('%s','now');
INSERT INTO celebrities (id,name_ko,group_name,gender,animal_face,created_at,updated_at) VALUES ('bigbang_top','탑','빅뱅','m','dino',strftime('%s','now'),strftime('%s','now')) ON CONFLICT(id) DO UPDATE SET gender=excluded.gender, animal_face=excluded.animal_face, updated_at=strftime('%s','now');
INSERT INTO celebrities (id,name_ko,group_name,gender,animal_face,created_at,updated_at) VALUES ('cnblue_jungyonghwa','정용화','씨엔블루','m','dino',strftime('%s','now'),strftime('%s','now')) ON CONFLICT(id) DO UPDATE SET gender=excluded.gender, animal_face=excluded.animal_face, updated_at=strftime('%s','now');
INSERT INTO celebrities (id,name_ko,group_name,gender,animal_face,created_at,updated_at) VALUES ('lee_minho','이민호',NULL,'m','dino',strftime('%s','now'),strftime('%s','now')) ON CONFLICT(id) DO UPDATE SET gender=excluded.gender, animal_face=excluded.animal_face, updated_at=strftime('%s','now');
INSERT INTO celebrities (id,name_ko,group_name,gender,animal_face,created_at,updated_at) VALUES ('qwer_chodan','쵸단','QWER','f','dog',strftime('%s','now'),strftime('%s','now')) ON CONFLICT(id) DO UPDATE SET gender=excluded.gender, animal_face=excluded.animal_face, updated_at=strftime('%s','now');
INSERT INTO celebrities (id,name_ko,group_name,gender,animal_face,created_at,updated_at) VALUES ('newjeans_minji','민지','뉴진스','f','dog',strftime('%s','now'),strftime('%s','now')) ON CONFLICT(id) DO UPDATE SET gender=excluded.gender, animal_face=excluded.animal_face, updated_at=strftime('%s','now');
INSERT INTO celebrities (id,name_ko,group_name,gender,animal_face,created_at,updated_at) VALUES ('ive_anyujin','안유진','아이브','f','dog',strftime('%s','now'),strftime('%s','now')) ON CONFLICT(id) DO UPDATE SET gender=excluded.gender, animal_face=excluded.animal_face, updated_at=strftime('%s','now');
INSERT INTO celebrities (id,name_ko,group_name,gender,animal_face,created_at,updated_at) VALUES ('nmixx_jiwoo','지우','엔믹스','f','dog',strftime('%s','now'),strftime('%s','now')) ON CONFLICT(id) DO UPDATE SET gender=excluded.gender, animal_face=excluded.animal_face, updated_at=strftime('%s','now');
INSERT INTO celebrities (id,name_ko,group_name,gender,animal_face,created_at,updated_at) VALUES ('kang_daniel','강다니엘',NULL,'m','dog',strftime('%s','now'),strftime('%s','now')) ON CONFLICT(id) DO UPDATE SET gender=excluded.gender, animal_face=excluded.animal_face, updated_at=strftime('%s','now');
INSERT INTO celebrities (id,name_ko,group_name,gender,animal_face,created_at,updated_at) VALUES ('nam_joohyuk','남주혁',NULL,'m','dog',strftime('%s','now'),strftime('%s','now')) ON CONFLICT(id) DO UPDATE SET gender=excluded.gender, animal_face=excluded.animal_face, updated_at=strftime('%s','now');
INSERT INTO celebrities (id,name_ko,group_name,gender,animal_face,created_at,updated_at) VALUES ('park_bogum','박보검',NULL,'m','dog',strftime('%s','now'),strftime('%s','now')) ON CONFLICT(id) DO UPDATE SET gender=excluded.gender, animal_face=excluded.animal_face, updated_at=strftime('%s','now');
INSERT INTO celebrities (id,name_ko,group_name,gender,animal_face,created_at,updated_at) VALUES ('song_joongki','송중기',NULL,'m','dog',strftime('%s','now'),strftime('%s','now')) ON CONFLICT(id) DO UPDATE SET gender=excluded.gender, animal_face=excluded.animal_face, updated_at=strftime('%s','now');
INSERT INTO celebrities (id,name_ko,group_name,gender,animal_face,created_at,updated_at) VALUES ('jung_haein','정해인',NULL,'m','dog',strftime('%s','now'),strftime('%s','now')) ON CONFLICT(id) DO UPDATE SET gender=excluded.gender, animal_face=excluded.animal_face, updated_at=strftime('%s','now');
INSERT INTO celebrities (id,name_ko,group_name,gender,animal_face,created_at,updated_at) VALUES ('yena','최예나',NULL,'f','duck',strftime('%s','now'),strftime('%s','now')) ON CONFLICT(id) DO UPDATE SET gender=excluded.gender, animal_face=excluded.animal_face, updated_at=strftime('%s','now');
INSERT INTO celebrities (id,name_ko,group_name,gender,animal_face,created_at,updated_at) VALUES ('classy_boeun','박보은','클라씨','f','duck',strftime('%s','now'),strftime('%s','now')) ON CONFLICT(id) DO UPDATE SET gender=excluded.gender, animal_face=excluded.animal_face, updated_at=strftime('%s','now');
INSERT INTO celebrities (id,name_ko,group_name,gender,animal_face,created_at,updated_at) VALUES ('ive_gaeul','가을','아이브','f','fennec',strftime('%s','now'),strftime('%s','now')) ON CONFLICT(id) DO UPDATE SET gender=excluded.gender, animal_face=excluded.animal_face, updated_at=strftime('%s','now');
INSERT INTO celebrities (id,name_ko,group_name,gender,animal_face,created_at,updated_at) VALUES ('kissoflife_haneul','하늘','키스오브라이프','f','fennec',strftime('%s','now'),strftime('%s','now')) ON CONFLICT(id) DO UPDATE SET gender=excluded.gender, animal_face=excluded.animal_face, updated_at=strftime('%s','now');
INSERT INTO celebrities (id,name_ko,group_name,gender,animal_face,created_at,updated_at) VALUES ('tripleS_xinyu','신위','트리플에스','f','fennec',strftime('%s','now'),strftime('%s','now')) ON CONFLICT(id) DO UPDATE SET gender=excluded.gender, animal_face=excluded.animal_face, updated_at=strftime('%s','now');
INSERT INTO celebrities (id,name_ko,group_name,gender,animal_face,created_at,updated_at) VALUES ('gang_dongwon','강동원',NULL,'m','fennec',strftime('%s','now'),strftime('%s','now')) ON CONFLICT(id) DO UPDATE SET gender=excluded.gender, animal_face=excluded.animal_face, updated_at=strftime('%s','now');
INSERT INTO celebrities (id,name_ko,group_name,gender,animal_face,created_at,updated_at) VALUES ('winner_kangseungyoon','강승윤','위너','m','fennec',strftime('%s','now'),strftime('%s','now')) ON CONFLICT(id) DO UPDATE SET gender=excluded.gender, animal_face=excluded.animal_face, updated_at=strftime('%s','now');
INSERT INTO celebrities (id,name_ko,group_name,gender,animal_face,created_at,updated_at) VALUES ('lee_joongi','이준기',NULL,'m','fennec',strftime('%s','now'),strftime('%s','now')) ON CONFLICT(id) DO UPDATE SET gender=excluded.gender, animal_face=excluded.animal_face, updated_at=strftime('%s','now');
INSERT INTO celebrities (id,name_ko,group_name,gender,animal_face,created_at,updated_at) VALUES ('gdragon','지드래곤',NULL,'m','fennec',strftime('%s','now'),strftime('%s','now')) ON CONFLICT(id) DO UPDATE SET gender=excluded.gender, animal_face=excluded.animal_face, updated_at=strftime('%s','now');
INSERT INTO celebrities (id,name_ko,group_name,gender,animal_face,created_at,updated_at) VALUES ('newjeans_hyein','혜인','뉴진스','f','hamster',strftime('%s','now'),strftime('%s','now')) ON CONFLICT(id) DO UPDATE SET gender=excluded.gender, animal_face=excluded.animal_face, updated_at=strftime('%s','now');
INSERT INTO celebrities (id,name_ko,group_name,gender,animal_face,created_at,updated_at) VALUES ('illit_wonhee','원희','아일릿','f','hamster',strftime('%s','now'),strftime('%s','now')) ON CONFLICT(id) DO UPDATE SET gender=excluded.gender, animal_face=excluded.animal_face, updated_at=strftime('%s','now');
INSERT INTO celebrities (id,name_ko,group_name,gender,animal_face,created_at,updated_at) VALUES ('highkey_yel','옐','하이키','f','hamster',strftime('%s','now'),strftime('%s','now')) ON CONFLICT(id) DO UPDATE SET gender=excluded.gender, animal_face=excluded.animal_face, updated_at=strftime('%s','now');
INSERT INTO celebrities (id,name_ko,group_name,gender,animal_face,created_at,updated_at) VALUES ('lightsum_yujeong','유정','라잇썸','f','rabbit',strftime('%s','now'),strftime('%s','now')) ON CONFLICT(id) DO UPDATE SET gender=excluded.gender, animal_face=excluded.animal_face, updated_at=strftime('%s','now');
INSERT INTO celebrities (id,name_ko,group_name,gender,animal_face,created_at,updated_at) VALUES ('billlie_tsuki','츠키','빌리','f','rabbit',strftime('%s','now'),strftime('%s','now')) ON CONFLICT(id) DO UPDATE SET gender=excluded.gender, animal_face=excluded.animal_face, updated_at=strftime('%s','now');
INSERT INTO celebrities (id,name_ko,group_name,gender,animal_face,created_at,updated_at) VALUES ('ive_wonyoung','장원영','아이브','f','rabbit',strftime('%s','now'),strftime('%s','now')) ON CONFLICT(id) DO UPDATE SET gender=excluded.gender, animal_face=excluded.animal_face, updated_at=strftime('%s','now');
INSERT INTO celebrities (id,name_ko,group_name,gender,animal_face,created_at,updated_at) VALUES ('illit_minju','민주','아일릿','f','rabbit',strftime('%s','now'),strftime('%s','now')) ON CONFLICT(id) DO UPDATE SET gender=excluded.gender, animal_face=excluded.animal_face, updated_at=strftime('%s','now');
INSERT INTO celebrities (id,name_ko,group_name,gender,animal_face,created_at,updated_at) VALUES ('ive_leeseo','이서','아이브','f','tiger',strftime('%s','now'),strftime('%s','now')) ON CONFLICT(id) DO UPDATE SET gender=excluded.gender, animal_face=excluded.animal_face, updated_at=strftime('%s','now');
INSERT INTO celebrities (id,name_ko,group_name,gender,animal_face,created_at,updated_at) VALUES ('illit_yunah','윤아','아일릿','f','tiger',strftime('%s','now'),strftime('%s','now')) ON CONFLICT(id) DO UPDATE SET gender=excluded.gender, animal_face=excluded.animal_face, updated_at=strftime('%s','now');
INSERT INTO celebrities (id,name_ko,group_name,gender,animal_face,created_at,updated_at) VALUES ('highkey_hwiseo','휘서','하이키','f','tiger',strftime('%s','now'),strftime('%s','now')) ON CONFLICT(id) DO UPDATE SET gender=excluded.gender, animal_face=excluded.animal_face, updated_at=strftime('%s','now');
INSERT INTO celebrities (id,name_ko,group_name,gender,animal_face,created_at,updated_at) VALUES ('park_haejin','박해진',NULL,'m','wolf',strftime('%s','now'),strftime('%s','now')) ON CONFLICT(id) DO UPDATE SET gender=excluded.gender, animal_face=excluded.animal_face, updated_at=strftime('%s','now');
INSERT INTO celebrities (id,name_ko,group_name,gender,animal_face,created_at,updated_at) VALUES ('so_jisub','소지섭',NULL,'m','wolf',strftime('%s','now'),strftime('%s','now')) ON CONFLICT(id) DO UPDATE SET gender=excluded.gender, animal_face=excluded.animal_face, updated_at=strftime('%s','now');
INSERT INTO celebrities (id,name_ko,group_name,gender,animal_face,created_at,updated_at) VALUES ('won_bin','원빈',NULL,'m','wolf',strftime('%s','now'),strftime('%s','now')) ON CONFLICT(id) DO UPDATE SET gender=excluded.gender, animal_face=excluded.animal_face, updated_at=strftime('%s','now');
